In [24]:
print("Hello, World!")

Hello, World!


In [25]:
print("name:yahya")
print("age:22")
print("color:blue")

name:yahya
age:22
color:blue


In [26]:
def welcome(name):
    """print welcome not to the output."""
    print(f"hello {name}")
welcome("shadi")


hello shadi


In [27]:
print(help(welcome))

Help on function welcome in module __main__:

welcome(name)
    print welcome not to the output.

None


In [32]:
help("keywords")


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



In [29]:
v1,v2,v3=1,2,3
print(v1,v2,v3)

1 2 3


In [30]:
height=180
print("the height is:", height)

the height is: 180


In [31]:
number_of_apples =int(10)
print("the number of apples is:", type(number_of_apples))
pi_value =float(3.14)
print("the pi value is:", type(pi_value))
is_sunny =bool(True)
print("is it sunny today?",type(is_sunny))
greeting =str("good morning")
print("the type of greeting is:", type(greeting))

the number of apples is: <class 'int'>
the pi value is: <class 'float'>
is it sunny today? <class 'bool'>
the type of greeting is: <class 'str'>


In [3]:
x=eval(input("enter a number:"))
print(x)
print(type(x))

5.5
<class 'float'>


In [11]:
name=input("enter your name:")
age =eval(input("enter your age:"))
print("hello", name, "your age is", age ,"years you need to be 100 years old in", 100-age)

hello yay your age is 22 years you need to be 100 years old in 78


In [13]:
import sys
print(sys.executable)


c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\python.exe


In [15]:
import sys
!{sys.executable} -m pip install pandas



[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [18]:
import sys
!{sys.executable} -m pip install scikit-learn



[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
import sklearn as sk
print(sk.__version__)

1.7.1


In [4]:
name = "yahya"
age = 22    
x= 10
print("hello {} your age is {} and the value of x is {}".format(name,age,x))
print(f"hello {name} your age is {age} and the value of x is {x}")
print("hello %s your age is %d and the value of x is %d"%(name,age,x))
print("hello",name,"your age is",age,"and the value of x is",x)
print("hello {n} your age is {a} and the value of x is {x}".format(n=name,a=age,x=x))


hello yahya your age is 22 and the value of x is 10
hello yahya your age is 22 and the value of x is 10
hello yahya your age is 22 and the value of x is 10
hello yahya your age is 22 and the value of x is 10
hello yahya your age is 22 and the value of x is 10


In [6]:
temprerature=35.265398457
print("the temprature is %.2f"%temprerature)
print(f"the temprature is {temprerature:.3f}")       

the temprature is 35.27
the temprature is 35.265


In [10]:
s=0.6557
print(f"{s:.2} text message here")
print(f"{s:.2%} text message here")

0.66 text message here
65.57% text message here


In [12]:
name=input("enter your name:")
favorite_food=input("enter your favorite food:")
print(f"hello {name} your favorite food is {favorite_food}")

hello yahya your favorite food is lkfklsa


In [13]:
import sys
!{sys.executable} -m pip install torch torchvision torchaudio

   ---------------------------------------- 0.0/241.4 MB ? eta -:--:--
   ---------------------------------------- 0.1/241.4 MB 2.0 MB/s eta 0:02:02
   ---------------------------------------- 0.2/241.4 MB 2.5 MB/s eta 0:01:37
   ---------------------------------------- 0.5/241.4 MB 3.8 MB/s eta 0:01:04
   ---------------------------------------- 1.2/241.4 MB 6.7 MB/s eta 0:00:37
   ---------------------------------------- 2.5/241.4 MB 11.3 MB/s eta 0:00:22
   ---------------------------------------- 3.0/241.4 MB 12.6 MB/s eta 0:00:19
    --------------------------------------- 4.9/241.4 MB 15.5 MB/s eta 0:00:16
   - -------------------------------------- 7.4/241.4 MB 20.5 MB/s eta 0:00:12
   - -------------------------------------- 9.8/241.4 MB 24.0 MB/s eta 0:00:10
   - -------------------------------------- 11.4/241.4 MB 36.4 MB/s eta 0:00:07
   -- ------------------------------------- 14.3/241.4 MB 50.4 MB/s eta 0:00:05
   -- ------------------------------------- 16.7/241.4 MB 50.1

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import torch
print(torch.__version__)

2.8.0+cpu


In [20]:
print("yahya\raaj")

aajya


In [38]:
text="yahya loves python and python is easy and python is popular   language and python is good for data science"
print(text.count("python"))
print(text.find("python"))
print(text.find("g"))
print(text.replace("python","java"))
print(text.upper())
print(len(text))
print(text.strip())
print(text.split(" ")) 

4
12
65
yahya loves java and java is easy and java is popular   language and java is good for data science
YAHYA LOVES PYTHON AND PYTHON IS EASY AND PYTHON IS POPULAR   LANGUAGE AND PYTHON IS GOOD FOR DATA SCIENCE
106
yahya loves python and python is easy and python is popular   language and python is good for data science
['yahya', 'loves', 'python', 'and', 'python', 'is', 'easy', 'and', 'python', 'is', 'popular', '', '', 'language', 'and', 'python', 'is', 'good', 'for', 'data', 'science']


In [33]:
print(help(list))

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

In [ ]:
print(help(list.append))

print(help(list.__add__))

Help on method_descriptor:

append(self, object, /) unbound builtins.list method
    Append object to the end of the list.

None
Help on wrapper_descriptor:

__add__(self, value, /) unbound builtins.list method
    Return self+value.

None


In [37]:
x=eval(input("enter a number:"))
print(x)
if x<0:
    print("the number is negative") 
elif x==0:
    print("the number is zero")
else:
    print("the number is positive")

5
the number is positive


In [1]:
num=eval(input("enter a number:"))
country =input("enter your country:")
if num>=18:
    if country.lower()=="jordan":
        print("you are allowed to vote")
    else:
        print("your are an adule, bout not form jordan")
else:
    print("you are not allowed to vote")

you are not allowed to vote


In [4]:
thislist = ["apple", "banana", "cherry"]
tropical = ["mango", "pineapple", "papaya"]
thislist.extend(tropical)
print(thislist)

['apple', 'banana', 'cherry', 'mango', 'pineapple', 'papaya']


In [ ]:
list1=["apple", "banana", "cherry", "orange", "kiwi", "melon"]
print(list1)
print(len(list1[1]))
print(list1[-2])
print(list1[1:3])


['apple', 'banana', 'cherry', 'orange', 'kiwi', 'melon']
6
kiwi
['banana', 'cherry']
1


In [14]:
thislist = ["apple", "banana", "cherry"]
thistuple = ("kiwi", "orange")
thislist.extend(thistuple)
print(thislist)

['apple', 'banana', 'cherry', 'kiwi', 'orange']


In [26]:
list2=[1,2,3]
list2.append(4)
print(list2)
list2.insert(1,5)
print(list2)
print(list2.count(2))

list2.index(3)

[1, 2, 3, 4]
[1, 5, 2, 3, 4]
1


3

In [29]:
nested_list=[[1,2,3],[4,5,6],[7,8,9]]
number=nested_list[1][1]
print(number)
nested_list[2].append(10)
print(nested_list)

5
[[1, 2, 3], [4, 5, 6], [7, 8, 9, 10]]


In [39]:
tuple1=("apple", "banana", "cherry")
len(tuple1)
print(len(tuple1))
print(tuple1[2])

3
cherry


In [5]:
import torch
import torchvision
import torchaudio

print(torch.__version__)        # 2.7.1+cu118
print(torchvision.__version__)  # 0.22.1+cu118
print(torchaudio.__version__)   # 2.7.1+cu118
print(torch.cuda.is_available()) # يجب أن تُرجع True


2.8.0+cpu
0.23.0+cpu
2.8.0+cpu
False


In [9]:
set2=set()
set3={1,2,3}
set2.update(set3)
print(set2)
# or ######################################
set1=set()
set1.add(1)
set1.add(2) 
set1.add(3)
print(set1)

{1, 2, 3}
{1, 2, 3}


In [ ]:
task1={1,2,3,4}
print(task1)  
if 2 in task1:  
    print("2 is in the set")
else:
    print("2 is not in the set")
if 5  in task1:  
    print("5 is in the set")
else:
    print("5 is not in the set")

{1, 2, 3, 4}
2 is in the set
5 is not in the set


In [11]:
A = {"red", "green", "blue"}
B= {"red", "pink", "yellow"}
result = A | B
print(result)
result2 = A.intersection(B)
print(result2)
result3=A.difference(B)
print(result3)
B=A|B
print(B)

{'green', 'blue', 'red', 'yellow', 'pink'}
{'red'}
{'green', 'blue'}
{'green', 'blue', 'red', 'yellow', 'pink'}


In [ ]:
d={"one":{1,2,3,4}, "two":2, "three":3}
print(d)
print(d["one"])


{'one': {1, 2, 3, 4}, 'two': 2, 'three': 3}
{1, 2, 3, 4}


In [ ]:
students = {"student1":{"name":"yahya",
                        "age":22,
                        "course":"python data science"}}
students["student1"].update({"phon_number":"0791234567"})
students["student1"].update({"age":23})
print(students.items())
students["student1"].popitem()
print(students)


dict_items([('student1', {'name': 'yahya', 'age': 23, 'course': 'python data science', 'phon_number': '0791234567'})])
{'student1': {'name': 'yahya', 'age': 23, 'course': 'python data science'}}


In [1]:
for i in range(5,0,-1):
    for j in range(i):
        print("*",end="")
    print()
#*******************************************************************************************
for i in range(6):
    for j in range(i):
        print("*",end="")
    print()



*****
****
***
**
*

*
**
***
****
*****


In [3]:
names=["yahya","shadi","mohammad","ahmad"]
scores=[90,85,80,95]
res=zip(names,scores)
print(list(res))
print(res)

[('yahya', 90), ('shadi', 85), ('mohammad', 80), ('ahmad', 95)]


In [6]:
i=0
while i<3:
    print(i)
    i+=1

0
1
2


In [10]:
i=0
while i<=10:
    print(i)
    i+=1    

0
1
2
3
4
5
6
7
8
9
10


In [12]:
def factorial(n):
    result= n+1
    return result
print(factorial(5))

6


In [13]:
def ny_fun():
    pass

In [15]:
def fun():
    print("yahya")
fun()

yahya


In [21]:
def fun(first_name, last_name):
    print(first_name+last_name)
fun("yahya"," mahmoud")

yahya mahmoud


In [23]:
def fun(a,b=5):
    print(a+b)
fun(3)

8


In [25]:
def fun(name,number=5):
    print(name*number)
fun("yahya",3)

yahyayahyayahya


In [27]:
import numpy as np
mean=np.mean([10,20])
print(mean) 

15.0


In [34]:
def fun(list1:list):
    for i in list1:
        if i%2==0:
            print(i)
        else:
            print("odd",i)
fun([1,2,3,4,5,6,7,8,9,10])

odd 1
2
odd 3
4
odd 5
6
odd 7
8
odd 9
10


In [ ]:
def func(text):
    def inner_function():
       print(text)
    inner_function()
x=10
print(x)
func("hello")



10
hello


In [67]:
def outer_function(param_outer):
    # Code of the outer function

    def inner_function(param_inner):
        # Code of the inner function
        print(f"Inner function called with: {param_inner}")
        print(f"Accessing outer function's variable: {param_outer}")

    # Call the inner function from within the outer function
    inner_function("Hello from inner")

outer_function("Outer variable")

Inner function called with: Hello from inner
Accessing outer function's variable: Outer variable


In [79]:
x=[1, 2, 3]
y=["a"," b", "c"]
z = zip(x, y)
z_list = list(z)
print(z_list,end="\n"or" ")

import numpy as np
arr = np.array(z_list)
reshaped = arr.reshape(3, 2)  # 3 rows, 2 columns (since there are 3 pairs)
print(reshaped)
    

[(1, 'a'), (2, ' b'), (3, 'c')]
[['1' 'a']
 ['2' ' b']
 ['3' 'c']]


In [86]:
#EX1 
#strings:
#1.Write a function to count the number of vowels in a given string
def number_of_vowels(text):
  Vowels=["a","e","i","u","o"]
  cont=0
  text=text.lower()
  for i in text:
    if i in Vowels:
      cont+=1
  print(cont)
number_of_vowels("yahya loves python and python is easy and python is popular language and python is good for data science")


31


In [111]:
import nltk
from nltk.tokenize import  word_tokenize
def str_second_letter_capitalized(example_string):
    example_string=example_string.lower()
word_tokens = word_tokenize(example_string)
print(word_tokens)
for word in word_tokens:
    if word.isalpha():  
        word = word[0]+word[1].upper()+word[2:]
        print(word,end=" ")
    else:
        continue
#str_second_letter_capitalized(""" Muad'Dib learned rapidly because his first training was in how to learn.
#And the first lesson of all was the basic trust that he could learn. It's shocking to find how
#many people do not believe they can learn, and how many more believe learning to be
#difficult.""")

["Muad'Dib", 'learned', 'rapidly', 'because', 'his', 'first', 'training', 'was', 'in', 'how', 'to', 'learn', '.', 'And', 'the', 'first', 'lesson', 'of', 'all', 'was', 'the', 'basic', 'trust', 'that', 'he', 'could', 'learn', '.', 'It', "'s", 'shocking', 'to', 'find', 'how', 'many', 'people', 'do', 'not', 'believe', 'they', 'can', 'learn', ',', 'and', 'how', 'many', 'more', 'believe', 'learning', 'to', 'be', 'difficult', '.']
lEarned rApidly bEcause hIs fIrst tRaining wAs iN hOw tO lEarn ANd tHe fIrst lEsson oF aLl wAs tHe bAsic tRust tHat hE cOuld lEarn IT sHocking tO fInd hOw mAny pEople dO nOt bElieve tHey cAn lEarn aNd hOw mAny mOre bElieve lEarning tO bE dIfficult 

In [104]:
def str_second_letter_capitalized(text):
  text=text[0]+text[1].upper()+text[2:]
  print(text)
str_second_letter_capitalized("yahya")

yAhya


In [1]:
import numpy as np 

In [8]:
x=np.zeros((11,11))
y=len(x)
y

11

In [9]:
for i in range(len(x)):
    for j in range (len(x)):
        x[i][j]=i*j
print(x)

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  0.   3.   6.   9.  12.  15.  18.  21.  24.  27.  30.]
 [  0.   4.   8.  12.  16.  20.  24.  28.  32.  36.  40.]
 [  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.]
 [  0.   6.  12.  18.  24.  30.  36.  42.  48.  54.  60.]
 [  0.   7.  14.  21.  28.  35.  42.  49.  56.  63.  70.]
 [  0.   8.  16.  24.  32.  40.  48.  56.  64.  72.  80.]
 [  0.   9.  18.  27.  36.  45.  54.  63.  72.  81.  90.]
 [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]


In [11]:
import math
math.sqrt(25)

5.0